# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - doxygen
    - graphviz
    - texlive-font-utils
  tools:
    python: "3.12"
  jobs:
    pre_install:
      - pwd
    post_build:
      - pwd
      - ls 
      - ls docs
      - ls docs/madara
      - ls docs/build
      - ls _readthedocs
      - cp -rf docs/madara/* _readthedocs/

sphinx:
  configuration: docs/conf.py

