
#ifndef   _THREAD_MYTHREAD_H_
#define   _THREAD_MYTHREAD_H_

#include <string>

#include "madara/threads/BaseThread.h"

namespace threads
{
  /**
  * A custom thread generated by mpg.pl
  **/
  class MyThread : public madara::threads::BaseThread
  {
  public:
    /**
     * Default constructor
     **/
    MyThread ();
    
    /**
     * Destructor
     **/
    virtual ~MyThread ();
    
    /**
      * Initializes thread with MADARA knowledge base
      * @param   kb   context for querying current program state
      **/
    virtual void init (madara::knowledge::KnowledgeBase & kb);

    /**
      * Executes the main thread logic
      **/
    virtual void run (void);

  private:
    /// data plane if we want to access the knowledge base
    madara::knowledge::KnowledgeBase data_;
  };
} // end namespace threads

#endif // _THREAD_MYTHREAD_H_

