///////////////////////////////////////////////////////////////////////////
// ComponentConfig.h, component configuration parameters.
//
// Initially generated by the component wizard. Feel free to manually edit.
///////////////////////////////////////////////////////////////////////////

// Component framework type
#define BON2COMPONENT

// COM UUID-s, names and progID
#define TYPELIB_UUID "FD3BE28A-E167-49FB-9005-5F7998F7AE76"
#define TYPELIB_NAME "MGA Interpreter TypeLibrary (GenerateXML)"
#define COCLASS_UUID "B47E411A-4357-44B7-93B2-22BDF3931D36"
#define COCLASS_NAME "MGA Interpreter CoClass (GenerateXML)"
#define COCLASS_PROGID "MGA.Interpreter.GenerateXML"

#define COCLASS_UUID_EXPLODED1  0xb47e411a
#define COCLASS_UUID_EXPLODED2   0x4357
#define COCLASS_UUID_EXPLODED3   0x44b7
#define COCLASS_UUID_EXPLODED4   0x93
#define COCLASS_UUID_EXPLODED5   0xb2
#define COCLASS_UUID_EXPLODED6   0x22
#define COCLASS_UUID_EXPLODED7   0xbd
#define COCLASS_UUID_EXPLODED8   0xf3
#define COCLASS_UUID_EXPLODED9   0x93
#define COCLASS_UUID_EXPLODED10  0x1d
#define COCLASS_UUID_EXPLODED11  0x36


// This name will appear in the popup window for interpreter selection.
#define COMPONENT_NAME "GenerateXML"


// This text will appear in the toolbar icon tooltip and in the menu.
#define TOOLTIP_TEXT "Generate XML from KATS model"

// This macro determines the component type (addon vs. interpreter):
#define GME_INTERPRETER

// The name of the paradigm(s). The GME will use this component
// for this paradigm. Separate the names of paradigms by commas.
#define PARADIGMS "KATS"


#define BON_ICON_SUPPORT

// not defined: #define BON_CUSTOM_TRANSACTIONS

#define REGISTER_SYSTEMWIDE
