/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MadaraExport.h"
/* Header for class ai_madara_knowledge_containers_CircularBuffer */

#ifndef _Included_ai_madara_knowledge_containers_CircularBuffer
#define _Included_ai_madara_knowledge_containers_CircularBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_CircularBuffer
 * Signature: ()J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1CircularBuffer__(
    JNIEnv*, jobject);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_CircularBuffer
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1CircularBuffer__J(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_freeCircularBuffer
 * Signature: (J)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1freeCircularBuffer(
    JNIEnv*, jclass, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_addRecord
 * Signature: (JJ)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1addRecord(
    JNIEnv*, jobject, jlong, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_addRecordVector
 * Signature: (J[J)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1addRecordVector(
    JNIEnv*, jobject, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_getRecord
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1getRecord(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_getEarliestRecordVector
 * Signature: (JI)[Ljava/lang/Object;
 */
MADARA_EXPORT jobjectArray JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1getEarliestRecordVector(
    JNIEnv*, jobject, jlong, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_getLatestRecordVector
 * Signature: (JI)[Ljava/lang/Object;
 */
MADARA_EXPORT jobjectArray JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1getLatestRecordVector(
    JNIEnv*, jobject, jlong, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_inspectRecord
 * Signature: (JI)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1inspectRecord(
    JNIEnv*, jobject, jlong, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_inspectRecordVector
 * Signature: (JII)[Ljava/lang/Object;
 */
MADARA_EXPORT jobjectArray JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1inspectRecordVector(
    JNIEnv*, jobject, jlong, jint, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
MADARA_EXPORT jstring JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1getName(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1setName(
    JNIEnv*, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_size
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1size(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_clear
 * Signature: ()V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1clear(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_count
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1count(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_resize
 * Signature: (JJ)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1resize(
    JNIEnv*, jobject, jlong, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBuffer
 * Method:    jni_setSettings
 * Signature: (JJ)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBuffer_jni_1setSettings(
    JNIEnv*, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
