/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MadaraExport.h"
/* Header for class ai_madara_logger_Logger */

#ifndef _Included_ai_madara_logger_Logger
#define _Included_ai_madara_logger_Logger
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_Logger
 * Signature: ()J
 */
MADARA_EXPORT jlong JNICALL Java_ai_madara_logger_Logger_jni_1Logger__(
    JNIEnv*, jobject);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_freeLogger
 * Signature: (J)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1freeLogger(
    JNIEnv*, jclass, jlong);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_setLevel
 * Signature: (JI)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1setLevel(
    JNIEnv*, jobject, jlong, jint);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_getLevel
 * Signature: (J)I
 */
MADARA_EXPORT jint JNICALL Java_ai_madara_logger_Logger_jni_1getLevel(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_getTag
 * Signature: (J)Ljava/lang/String;
 */
MADARA_EXPORT jstring JNICALL Java_ai_madara_logger_Logger_jni_1getTag(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_setTag
 * Signature: (JLjava/lang/String;)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1setTag(
    JNIEnv*, jobject, jlong, jstring);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_addTerm
 * Signature: (J)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1addTerm(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_addSyslog
 * Signature: (J)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1addSyslog(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_clear
 * Signature: (J)J
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1clear(
    JNIEnv*, jobject, jlong);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_addFile
 * Signature: (JLjava/lang/String;)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1addFile(
    JNIEnv*, jobject, jlong, jstring);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_log
 * Signature: (JLjava/lang/String;)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1log(
    JNIEnv*, jobject, jlong, jint, jstring);

/*
 * Class:     ai_madara_logger_Logger
 * Method:    jni_setTimestampFormat
 * Signature: (JLjava/lang/String;)V
 */
MADARA_EXPORT void JNICALL Java_ai_madara_logger_Logger_jni_1setTimestampFormat(
    JNIEnv*, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
