/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_madara_knowledge_AnyRef */

#ifndef _Included_ai_madara_knowledge_AnyRef
#define _Included_ai_madara_knowledge_AnyRef
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_field
 * Signature: (Ljava/lang/String;JJ[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1field(
    JNIEnv*, jclass, jstring, jlong, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_index
 * Signature: (Ljava/lang/String;JJ[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_ai_madara_knowledge_AnyRef_jni_1index__Ljava_lang_String_2JJ_3J(
    JNIEnv*, jclass, jstring, jlong, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_index
 * Signature: (JJJ[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1index__JJJ_3J(
    JNIEnv*, jclass, jlong, jlong, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_assign
 * Signature: (JJJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1assign__JJJJ(
    JNIEnv*, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_assign_record
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1assign_1record(
    JNIEnv*, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_assign
 * Signature: (JJJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1assign__JJJ(
    JNIEnv*, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_assign
 * Signature: (JJD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1assign__JJD(
    JNIEnv*, jclass, jlong, jlong, jdouble);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_assign
 * Signature: (JJLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_ai_madara_knowledge_AnyRef_jni_1assign__JJLjava_lang_String_2(
    JNIEnv*, jclass, jlong, jlong, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_assign
 * Signature: (JJ[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1assign__JJ_3J(
    JNIEnv*, jclass, jlong, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_assign
 * Signature: (JJ[D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1assign__JJ_3D(
    JNIEnv*, jclass, jlong, jlong, jdoubleArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_to_record
 * Signature: (JJ[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1to_1record(
    JNIEnv*, jclass, jlong, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_to
 * Signature: (JJ[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1to__JJ_3J(
    JNIEnv*, jclass, jlong, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_to
 * Signature: (JJ[D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1to__JJ_3D(
    JNIEnv*, jclass, jlong, jlong, jdoubleArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_to
 * Signature: (JJ[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_ai_madara_knowledge_AnyRef_jni_1to__JJ_3Ljava_lang_String_2(
    JNIEnv*, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_to
 * Signature: (JJ[[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1to__JJ_3_3J(
    JNIEnv*, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_to
 * Signature: (JJ[[D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1to__JJ_3_3D(
    JNIEnv*, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_size
 * Signature: (JJ[J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1size(
    JNIEnv*, jclass, jlong, jlong, jlongArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_list_fields
 * Signature: (JJ[[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1list_1fields(
    JNIEnv*, jclass, jlong, jlong, jobjectArray);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_get_tag
 * Signature: (JJ[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1get_1tag(
    JNIEnv*, jclass, jlong, jlong, jobjectArray);

#ifdef _USE_CAPNP_
/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_register_tag
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1register_1tag(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    jni_reader
 * Signature: (JJ[[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ai_madara_knowledge_AnyRef_jni_1reader(
    JNIEnv*, jclass, jlong, jlong, jobjectArray);
#endif

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerInt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerInt(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerLong
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerLong(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerShort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerShort(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerChar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerChar(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerUInt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerUInt(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerULong
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerULong(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerUShort
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerUShort(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerUChar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerUChar(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerSChar
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerSChar(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerDouble
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerDouble(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerFloat
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerFloat(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerString(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerIntVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerIntVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerLongVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerLongVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerShortVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerShortVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerCharVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerCharVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerUIntVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerUIntVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerULongVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerULongVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerUShortVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerUShortVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerUCharVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerUCharVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerSCharVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerSCharVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerDoubleVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerDoubleVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerFloatVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerFloatVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerStringVector
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerStringVector(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerStringToStringMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_ai_madara_knowledge_AnyRef_registerStringToStringMap(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerStringToLongMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ai_madara_knowledge_AnyRef_registerStringToLongMap(
    JNIEnv*, jclass, jstring);

/*
 * Class:     ai_madara_knowledge_AnyRef
 * Method:    registerStringToDoubleMap
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL
Java_ai_madara_knowledge_AnyRef_registerStringToDoubleMap(
    JNIEnv*, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
