/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MadaraExport.h"
/* Header for class ai_madara_knowledge_containers_CircularBufferConsumer */

#ifndef _Included_ai_madara_knowledge_containers_CircularBufferConsumer
#define _Included_ai_madara_knowledge_containers_CircularBufferConsumer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_CircularBufferConsumer
 * Signature: ()J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1CircularBufferConsumer__
  (JNIEnv *, jobject);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_CircularBufferConsumer
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1CircularBufferConsumer__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_freeCircularBufferConsumer
 * Signature: (J)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1freeCircularBufferConsumer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_consumeRecord
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1consumeRecord
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_consumeEarliestRecordVector
 * Signature: (JI)[Ljava/lang/Object;
 */
MADARA_EXPORT jobjectArray JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1consumeEarliestRecordVector
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_consumeLatestRecordVector
 * Signature: (JI)[Ljava/lang/Object;
 */
MADARA_EXPORT jobjectArray JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1consumeLatestRecordVector
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_inspectRecord
 * Signature: (JI)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1inspectRecord
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_inspectRecordVector
 * Signature: (JII)[Ljava/lang/Object;
 */
MADARA_EXPORT jobjectArray JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1inspectRecordVector
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_peekRecord
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1peekRecord
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_peekRecordVector
 * Signature: (JI)[Ljava/lang/Object;
 */
MADARA_EXPORT jobjectArray JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1peekRecordVector
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
MADARA_EXPORT jstring JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_remaining
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1remaining
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_resync
 * Signature: (J)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1resync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_size
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_count
 * Signature: (J)J
 */
MADARA_EXPORT jlong JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_resize
 * Signature: (J)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1resize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_madara_knowledge_containers_CircularBufferConsumer
 * Method:    jni_setIndex
 * Signature: (JJ)V
 */
MADARA_EXPORT void JNICALL
Java_ai_madara_knowledge_containers_CircularBufferConsumer_jni_1setIndex
  (JNIEnv * env, jobject, jlong cptr, jlong index);

#ifdef __cplusplus
}
#endif
#endif
