/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MADARA_export.h"
/* Header for class com_madara_threads_Threader */

#ifndef _Included_com_madara_threads_Threader
#define _Included_com_madara_threads_Threader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_Threader
 * Signature: ()J
 */
MADARA_Export jlong JNICALL Java_com_madara_threads_Threader_jni_1Threader__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_Threader
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_threads_Threader_jni_1Threader__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_freeThreader
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1freeThreader
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_run
 * Signature: (JLjava/lang/String;Ljava/lang/Object;Z)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1run
  (JNIEnv *, jobject, jlong, jstring, jobject, jboolean);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_runhz
 * Signature: (JDLjava/lang/String;Ljava/lang/Object;Z)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1runhz
  (JNIEnv *, jobject, jlong, jdouble, jstring, jobject, jboolean);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_pauseThread
 * Signature: (JLjava/lang/String;)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1pauseThread
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_pause
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1pause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_waitThread
 * Signature: (JLjava/lang/String;)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1waitThread
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_wait
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1wait
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_terminateThread
 * Signature: (JLjava/lang/String;)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1terminateThread
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_terminate
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1terminate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_resumeThread
 * Signature: (JLjava/lang/String;)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1resumeThread
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_madara_threads_Threader
 * Method:    jni_resume
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_threads_Threader_jni_1resume
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
