/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MADARA_export.h"
/* Header for class com_madara_containers_Queue */

#ifndef _Included_com_madara_containers_Queue
#define _Included_com_madara_containers_Queue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_Queue
 * Signature: ()J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Queue_jni_1Queue__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_Queue
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Queue_jni_1Queue__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_freeQueue
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Queue_jni_1freeQueue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_enqueue
 * Signature: (JJ)Z
 */
MADARA_Export jboolean JNICALL Java_com_madara_containers_Queue_jni_1enqueue
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_enqueueDouble
 * Signature: (JD)Z
 */
MADARA_Export jboolean JNICALL Java_com_madara_containers_Queue_jni_1enqueueDouble
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_enqueueLong
 * Signature: (JJ)Z
 */
MADARA_Export jboolean JNICALL Java_com_madara_containers_Queue_jni_1enqueueLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_enqueueString
 * Signature: (JLcom/madara/containers/String;)Z
 */
MADARA_Export jboolean JNICALL Java_com_madara_containers_Queue_jni_1enqueueString
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_dequeue
 * Signature: (JZ)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Queue_jni_1dequeue
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_inspect
 * Signature: (JI)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Queue_jni_1inspect
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
MADARA_Export jstring JNICALL Java_com_madara_containers_Queue_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Queue_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_size
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Queue_jni_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_count
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Queue_jni_1count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_resize
 * Signature: (JJ)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Queue_jni_1resize
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_containers_Queue
 * Method:    jni_clear
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Queue_jni_1clear
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
