/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MADARA_export.h"
/* Header for class com_madara_containers_Barrier */

#ifndef _Included_com_madara_containers_Barrier
#define _Included_com_madara_containers_Barrier
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_Barrier
 * Signature: ()J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Barrier_jni_1Barrier__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_Barrier
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Barrier_jni_1Barrier__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_freeBarrier
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Barrier_jni_1freeBarrier
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_set
 * Signature: (JJ)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Barrier_jni_1set
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
MADARA_Export jstring JNICALL Java_com_madara_containers_Barrier_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Barrier_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
MADARA_Export jstring JNICALL Java_com_madara_containers_Barrier_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_toDouble
 * Signature: (J)D
 */
MADARA_Export jdouble JNICALL Java_com_madara_containers_Barrier_jni_1toDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_toLong
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Barrier_jni_1toLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_next
 * Signature: (J)J
 */
MADARA_Export void JNICALL Java_com_madara_containers_Barrier_jni_1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_isDone
 * Signature: (J)Z
 */
MADARA_Export jboolean JNICALL Java_com_madara_containers_Barrier_jni_1isDone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_modify
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Barrier_jni_1modify
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Barrier
 * Method:    jni_resize
 * Signature: (JII)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Barrier_jni_1resize
  (JNIEnv *, jobject, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
