/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MADARA_export.h"
/* Header for class com_madara_UpdateSettings */

#ifndef _Included_com_madara_UpdateSettings
#define _Included_com_madara_UpdateSettings
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_updateSettings
 * Signature: ()J
 */
MADARA_Export jlong JNICALL Java_com_madara_UpdateSettings_jni_1updateSettings__
  (JNIEnv *, jclass);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_updateSettings
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_UpdateSettings_jni_1updateSettings__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_setAlwaysOverwrite
 * Signature: (JZ)V
 */
MADARA_Export void JNICALL Java_com_madara_UpdateSettings_jni_1setAlwaysOverwrite
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_getAlwaysOverwrite
 * Signature: (J)Z
 */
MADARA_Export jboolean JNICALL Java_com_madara_UpdateSettings_jni_1getAlwaysOverwrite
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_setTreatGlobalsAsLocals
 * Signature: (JZ)V
 */
MADARA_Export void JNICALL Java_com_madara_UpdateSettings_jni_1setTreatGlobalsAsLocals
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_getTreatGlobalsAsLocals
 * Signature: (J)Z
 */
MADARA_Export jboolean JNICALL Java_com_madara_UpdateSettings_jni_1getTreatGlobalsAsLocals
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_setClockIncrement
 * Signature: (JJ)V
 */
MADARA_Export void JNICALL Java_com_madara_UpdateSettings_jni_1setClockIncrement
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_getClockIncrement
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_UpdateSettings_jni_1getClockIncrement
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_UpdateSettings
 * Method:    jni_freeUpdateSettings
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_UpdateSettings_jni_1freeUpdateSettings
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
