/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MADARA_export.h"
/* Header for class com_madara_filters_CounterFilter */

#ifndef _Included_com_madara_filters_CounterFilter
#define _Included_com_madara_filters_CounterFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_CounterFilter
 * Signature: ()J
 */
MADARA_Export jlong JNICALL Java_com_madara_filters_CounterFilter_jni_1CounterFilter__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_getThroughput
 * Signature: (J)D
 */
MADARA_Export jdouble JNICALL Java_com_madara_filters_CounterFilter_jni_1getThroughput
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_addReceiveFilterTo
 * Signature: (JJ)V
 */
MADARA_Export void JNICALL Java_com_madara_filters_CounterFilter_jni_1addReceiveFilterTo
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_addSendFilterTo
 * Signature: (JJ)V
 */
MADARA_Export void JNICALL Java_com_madara_filters_CounterFilter_jni_1addSendFilterTo
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_addRebroadcastFilterTo
 * Signature: (JJ)V
 */
MADARA_Export void JNICALL Java_com_madara_filters_CounterFilter_jni_1addRebroadcastFilterTo
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_getCount
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_filters_CounterFilter_jni_1getCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_getElapsed
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_filters_CounterFilter_jni_1getElapsed
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_filters_CounterFilter
 * Method:    jni_freeCounterFilter
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_filters_CounterFilter_jni_1freeCounterFilter
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
