/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "madara/MADARA_export.h"
/* Header for class com_madara_containers_Double */

#ifndef _Included_com_madara_containers_Double
#define _Included_com_madara_containers_Double
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_Double
 * Method:    jni_Double
 * Signature: ()J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Double_jni_1Double__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_Double
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Double_jni_1Double__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_freeDouble
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Double_jni_1freeDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_set
 * Signature: (JD)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Double_jni_1set
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
MADARA_Export jstring JNICALL Java_com_madara_containers_Double_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Double_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
MADARA_Export jstring JNICALL Java_com_madara_containers_Double_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_toDouble
 * Signature: (J)D
 */
MADARA_Export jdouble JNICALL Java_com_madara_containers_Double_jni_1toDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_toLong
 * Signature: (J)J
 */
MADARA_Export jlong JNICALL Java_com_madara_containers_Double_jni_1toLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_modify
 * Signature: (J)V
 */
MADARA_Export void JNICALL Java_com_madara_containers_Double_jni_1modify
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
