
module Ndds
{
  module Knowledge
  {
      typedef sequence<octet, 600000> seq_oct;
      struct Update
      {
        string                            originator; //@key
        seq_oct                           buffer;
        unsigned long                     quality;
        string                            madara_id;
        unsigned long                     updates;
        unsigned long                     type;
        unsigned long long                clock;
        unsigned long long                timestamp;
        unsigned long                     ttl;
      };  
  };
};